on:
  push:
    branches:

jobs:
  test:
    name: Test and lint sources
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    steps:
      - uses: actions/checkout@v2

      - name: Set up environment
        run: |
          set -o xtrace -o errexit
          pip install -e .[dev]

      - name: Linting
        run: |
          set -o xtrace -o errexit
          black --check src
          flake8 src
          mypy src
