name: Lint source and run tests

on:
  workflow_call:

jobs:
  lint_and_test:
    name: Lint source and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Set up environment
        run: |
          set -o xtrace -o errexit
          pip install -e .[dev]

      - name: Linting
        run: |
          set -o xtrace -o errexit
          black --check src
          flake8 src
          mypy src
